### ISSUE TITLE
Listing CocoaPods dependencies not working in CocoaPods 1.6.0.beta.1

### ISSUE THREAD

**Issue by datureezy** [mono0926/LicensePlist#92] opened 2018-10-17 23:44 UTC
Carthage dependencies have no problem being output, but with Cocoapods, I'm failing on all of my projects.

I have updated on Homebrew LicensePlist to the latest version along with on my project's Cocoapods.

I get this error when running license-plist when it's running through my Pods directory:

[2018-10-17T18:37:15.914-05:00] [INFO] Pod acknowledgements found: Pods-F-xxx-acknowledgements.plist
[2018-10-17T18:37:15.914-05:00] [INFO] Pod acknowledgements found: Pods-F-xxx-acknowledgements.plist
[2018-10-17T18:37:15.915-05:00] [INFO] Pod acknowledgements found: Pods-xxxExtension-acknowledgements.plist
[2018-10-17T18:37:15.918-05:00] [INFO] Pods License parse start
[2018-10-17T18:37:15.932-05:00] [ERROR] DecodeError.typeMismatch(expected: Dictionary, actual: , keyPath: KeyPath(["PreferenceSpecifiers"]))
[2018-10-17T18:37:15.932-05:00] [ERROR] DecodeError.typeMismatch(expected: Dictionary, actual: , keyPath: KeyPath(["PreferenceSpecifiers"]))
[2018-10-17T18:37:15.932-05:00] [ERROR] DecodeError.typeMismatch(expected: Dictionary, actual: , keyPath: KeyPath(["PreferenceSpecifiers"]))

I'm guessing that something must've changed in Cocoapod's code where LicensePlist isn't ready for such change.

**Comment by mono0926** [comment] 2018-10-18 00:04
Could you paste the result of `pod --version` like this?

```sh
pod --version
1.5.3
```

**Comment by datureezy** [comment] 2018-10-18 00:04
1.6.0.beta.1

Thank you for your quick response.

**Comment by mono0926** [comment] 2018-10-18 00:07
Does LicensePlist work with CocoaPods 1.5.3?
If so, the issue is related to CocoaPods 1.6.x and not related to Xcode 10, and I'll fix soon.

**Comment by datureezy** [comment] 2018-10-18 00:10
I'm not sure if it was 1.5.3, but it worked on my previous Cocoapods version. Sorry if I made it sound different, but I was presuming that a change in the updated Cocoapods was creating this issue since something changed from 'Dictionary' to ''. I agree that it's not Xcode 10, I should've been clearer. So many things changed for my computer, OS, Xcode, Cocoapods, Homebrew, and even License-Plist.

I will look forward to your change. Thank you again @mono0926!

**Comment by mono0926** [comment] 2018-10-18 00:13
Okay, thanks.
I suspect that this problem is related to CocoaPods 1.6.x for now, and I'll investigate it and try to fix this weekend 👌

**Comment by mono0926** [comment] 2018-10-21 12:01
> I suspect that this problem is related to CocoaPods 1.6.x for now, and I'll investigate it and try to fix this weekend 👌

Sorry, I couldn't take much time this week, I'll do it in a few days 🙏

**Comment by datureezy** [comment] 2018-10-21 14:36
Not a problem, Masayuki. More than thrilled that you upkeep this repository! Thank you.

**Comment by mono0926** [comment] 2018-10-22 07:58
It seems that that's `1.6.0.beta.1`'s bug( https://github.com/CocoaPods/CocoaPods/issues/8068 ) and it was fixed in `1.6.0.beta.2`.

I'll recommend you to upgrade to `1.6.0.beta.2` or use stable version `1.5.3`.

CocoaPods `1.6.x` is still beta and there are some problem like this issue, so I use `1.5.3` for now.

> I'll recommend you to update to `1.6.0.beta.2` or user stable version `1.5.3`.

After that, if the issue is fixed, close this.

**Closed** 2018-10-22 19:19 UTC
Labels: invalid, wontfix
